### ISSUE TITLE
RSpec Support

### ISSUE THREAD

**Issue by daphnegold** [daphnegold/adorables#1]
Addition of the RSpec gem (and Simplecov) + necessary additions to the `rails_helper.rb` file.

**Comment by jbuechs** [comment]
I'm not sure if I'm supposed to wait for you to finish this but I wanted to do some rspec for some of your project so I went ahead and added rspec and coverage to the project and created rspec files for models and controllers.

**Comment by daphnegold** [comment]
This totally slipped my mind. 🙌👍 You're awesome ^^
