### ISSUE TITLE
Hashtags for links

### ISSUE THREAD

**Issue by daphnegold** [daphnegold/adorables#19]
Ability to add hashtags to links that are searchable

**Comment by Kedevlin** [comment]
I'll work on this issue! :) :) Is the idea to create a Hashtag model, and then have a has_and_belongs_to_many relationship between Hashtag model and Link model?

**Comment by daphnegold** [comment]
I think that sounds great! I hadn't hashed (ha ha) out how to approach it. Just that it would be nice.

**Comment by Kedevlin** [comment]
Complete.  I just submitted a pull request.  Let me know if you need anything changed!

**Comment by daphnegold** [comment]
Ty so much @Kedevlin. Merged!
